src/Entity/CartItem.php
<?php
declare(strict_types = 1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Money\Money;
use Symfony\Component\Validator\Constraints as Assert;
use App\ValueObject\Quantity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CartItemRepository")
 * @ORM\Table(
 *     name="cart_items",
 *     uniqueConstraints={
 *        @UniqueConstraint(
 *            name="cart_item_unique",
 *            columns={"product_id", "shopping_cart_id"})
 *    })
 */
class CartItem
{
    /**
    * @ORM\Id()
    * @ORM\GeneratedValue(strategy="AUTO")
    * @ORM\Column(type="integer")
    * @var integer
    */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(
     *     targetEntity="Product"
     * )
     * @var Product
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=Quantity::MIN, max=Quantity::MAX)
     * @var integer
     */
    private $quantity = 1;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(
     *     targetEntity="ShoppingCart",
     *     inversedBy="cartItems"
     * )
     * @var ShoppingCart
     */
    private $shoppingCart;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @var \DateTimeImmutable
     */
    private $createAt;

    /**
     * @param Product      $product
     * @param ShoppingCart $shoppingCart
     * @param integer      $quantity
     * @throws \Exception Exception in case of an error.
     */
    public function __construct(Product $product, ShoppingCart $shoppingCart, int $quantity = 1)
    {
        $this->product      = $product;
        $this->shoppingCart = $shoppingCart;
        if ($quantity > 0) {
            $this->quantity = $quantity;
        }
        $this->createAt     = new \DateTimeImmutable();
    }

    /**
     * @return integer|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Product
     */
    public function getProduct(): Product
    {
        return $this->product;
    }

    /**
     * @return integer
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * @param integer $quantity
     */
    public function setQuantity(int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * @return ShoppingCart
     */
    public function getShoppingCart(): ShoppingCart
    {
        return $this->shoppingCart;
    }

    /**
     * @param ShoppingCart $shoppingCart
     */

    /**
     * @return \DateTimeImmutable
     */
    public function getCreateAt(): \DateTimeImmutable
    {
        return $this->createAt;
    }

    /**
     * @param integer $quantity
     * @return void
     */
    public function increaseQuantity(int $quantity = 1): void
    {
        if ($quantity < 1) {
            return ;
        }
        $this->quantity = $this->quantity + $quantity;
    }

    /**
     * @param integer $quantity
     * @return void
     */
    public function reduceQuantity(int $quantity = 1): void
    {
        if ($this->quantity < $quantity) {
            return ;
        }
        $this->quantity = $this->quantity - $quantity;
    }

    /**
     * @return Money
     */
    public function getCost(): Money
    {
        $quantity = $this->quantity;
        $price = $this->getProduct()->getPrice();
        $cost = $price;

        for ($i = 1; $i < $quantity; $i++) {
            $cost = $cost->add($price);
        }

        return $cost;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return sprintf('%s (X %d)', $this->getProduct()->getTitle(), $this->getQuantity());
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->shoppingCart->getUser();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{{ easyadmin_config('site_name') }}!{% endblock %}</title>

    {% block stylesheets %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% endblock %}
</head>
<body class="container-fluid">

<nav class="navbar navbar-expand-md">
    <a class="navbar-brand text-uppercase {{ easyadmin_config('site_name')|length > 14 ? 'logo-long' }}" title="{{ easyadmin_config('site_name')|striptags }}" href="{{ path('homepage') }}">
        {{ easyadmin_config('site_name')|raw }}
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
            <li><a href="{{ path("product_list") }}" class="btn btn-link">Products</a></li>
            {% if is_granted('ROLE_ADMIN') %}
            <li><a href="{{ path("easyadmin") }}" class="btn btn-link">Admin panel</a></li>
            {% endif %}
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
            <li><a href="{{ path('fos_user_profile_show') }}" class="nav-link disabled">{{ app.user.username }}</a></li>
            <li><a href="{{ path('shopping_cart') }}" class="nav-link">My Cart</a></li>
            <li><a href="{{ path('shopping_history') }}" class="nav-link">Shopping History</a></li>
            <li><a href="{{ path('fos_user_security_logout') }}" class="nav-link">Logout</a></li>
            {% else %}
            <li><a class="nav-link" href="{{ path('fos_user_security_login') }}">Login</a></li>
            <li><a class="nav-link" href="{{ path('fos_user_registration_register') }}">Register</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<h3>{{ block('title') }}</h3>

<div class="alerts">
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ label }}" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}
</div>

<div class="main-content">
    {% block aside %}{% endblock %}
    {% block body %}{% endblock %}
</div>

{% block javascripts %}
{% endblock %}
</body>

templates/index.html.twig
{% extends 'base.html.twig' %}

{%  block body %}
<ul>
    <li><a href="{{ path('easyadmin') }}">admin</a></li>
    <li><a href="{{ path('fos_user_security_login') }}">login</a></li>
    <li><a href="{{ path('fos_user_registration_register') }}">register</a></li>
    <li><a href="{{ path('fos_user_resetting_request') }}">reset password</a></li>
</ul>
{% endblock %}